# Setup
title: chw-owo
description: 차근차근 즐겁게
url: https://chw-owo.github.io
avatar: /avatar.jpeg
paginate: 10
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: chw-owo
  card: summary
logo: logo.png
social:
  name: Hyewon Cho
  links:
    - https://twitter.com/chw_owo
    - https://github.com/chw-owo
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Hyewon Cho
  url: https://github.com/chw-owo
  email: gpdnjs2116@gmail.com
